version: '3'
services:
  appcontainer:
    image: novacean/appimage:latest
    ports:
      - 8080:8080
    depends_on:
      - dbcontainer
    networks:
      appnetwork:
        aliases:
            - appcontainer
  dbcontainer:
    image: novacean/postgres:latest
    networks:
      appnetwork:
        aliases:
             - dbcontainer
    environment:
      - POSTGRES_DB=crudappdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
networks:
  appnetwork:
